version: '3.5'

services:
  redis:
    container_name: larry-redis
    image: redis
    ports:
      - 6379:6379
  larry:
    build: .
    environment:
      - REDIS_ADDRESS=larry-redis:6379
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
    entrypoint: sh -c "/larry --topic golang -x 1 --safe-mode"
    depends_on:
      - redis
  # ----
    
