version: '3.5'

services:
  redis:
    container_name: larry-redis
    image: redis
    ports:
      - 6379:6379
  larry:
    build: .
    environment:
      - REDIS_ADDRESS=larry-redis:6379
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
      - MASTODON_CLIENT_ID=${MASTODON_CLIENT_ID}
      - MASTODON_CLIENT_SECRET=${MASTODON_CLIENT_SECRET}
      - MASTODON_SERVER=${MASTODON_SERVER}
      - MASTODON_ACCESS_TOKEN=${MASTODON_ACCESS_TOKEN}
    entrypoint: sh -c "/larry --publisher=mastodon --topic golang -x 1 --safe-mode"
    depends_on:
      - redis
  # ----
    